import { parseCommand, CommandContext, CommandIntent, ParseResult } from "./parser";
import { Simulation } from "../sim/simulation";

export type OperatorCommandState="preview"|"clarification"|"confirmation"|"queued"|"executing"|"completed"|"failed"|"cancelled"|"superseded"|"rejected";
export interface OperatorCommand {id:string;input:string;createdAt:number;state:OperatorCommandState;parse:ParseResult;response:string;networkMessageId:string|null;}

export class CommandController{
  history:OperatorCommand[]=[];pending:OperatorCommand|null=null;private id=0;
  parse(input:string,context:CommandContext,now:number){const parsed=parseCommand(input,context),state:OperatorCommandState=parsed.status==="ready"?(parsed.confirmation==="routine"?"preview":"confirmation"):parsed.status==="clarification"||parsed.status==="target-required"?"clarification":"rejected";const command={id:`cmd-${++this.id}`,input,createdAt:now,state,parse:parsed,response:parsed.status==="ready"?`${parsed.canonical}: ${parsed.consequence}`:parsed.message,networkMessageId:null};this.pending=command;return command;}
  cancel(){if(!this.pending)return null;this.pending.state="cancelled";this.pending.response="Directive cancelled before execution.";this.history.push(this.pending);const c=this.pending;this.pending=null;return c;}
  execute(sim:Simulation,context:CommandContext,confirmed=false){const c=this.pending;if(!c||c.parse.status!=="ready")return null;if(c.parse.revision!==context.revision){c.state="rejected";c.response="Command rejected: tactical context changed; review the command again.";this.history.push(c);this.pending=null;return c;}if(c.parse.confirmation!=="routine"&&!confirmed){c.state="confirmation";return c;}c.state="queued";const result=applyIntent(sim,c.parse.intent);if(!result.ok){c.state="failed";c.response=result.message;}else{const msg=sim.queueNetworkMessage("operator","unit-ATLAS","operator",70,c.parse.confirmation==="critical"?4:8,sim.network.topologyRevision,null);c.networkMessageId=msg.id;c.state=msg.state==="delivered"?"executing":"queued";c.response=result.message;}if(this.history.at(-1)?.state==="executing")this.history.at(-1)!.state="superseded";this.history.push(c);this.pending=null;return c;}
  update(sim:Simulation){for(const command of this.history){if(!command.networkMessageId||!["queued","executing"].includes(command.state))continue;const message=sim.network.messages.find(m=>m.id===command.networkMessageId);if(!message)continue;if(message.state==="delivered"){command.state="completed";command.response=`Directive delivered and acknowledged: ${command.parse.status==="ready"?command.parse.canonical:"command"}.`;}else if(["expired","failed","superseded"].includes(message.state)){command.state="failed";command.response=`Command ${message.state}; no stale directive was applied.`;}}}
}

function applyIntent(sim:Simulation,intent:CommandIntent):{ok:boolean;message:string}{switch(intent.kind){case"hold":return{ok:sim.issueOrder("hold"),message:"Directive accepted. Fleet holding positions."};case"resume":sim.clearOrder();return{ok:true,message:"Directive accepted. NEREUS resumed autonomous planning."};case"regroup":return{ok:sim.issueOrder("regroup"),message:"Directive accepted. NEREUS is selecting a safe regroup plan."};case"retreat":if(sim.minefield)sim.updateMinefieldSettings({retreat:true});else sim.issueOrder("extract");return{ok:true,message:"Emergency withdrawal directive issued."};case"extract":return{ok:sim.issueOrder("extract"),message:"Extraction directive issued."};case"cancel":sim.clearOrder();return{ok:true,message:"Current directive cancelled; fleet holding under autonomy."};case"investigate":return{ok:!!intent.pos&&sim.issueOrder("investigate",intent.pos,intent.targetId),message:intent.pos?"Investigation directive issued.":"Investigation requires a resolved location."};case"focus":return{ok:!!intent.pos&&sim.issueOrder("advance",intent.pos,intent.targetId),message:intent.pos?"Focus-point directive issued.":"Focus point requires a resolved location."};case"protect":return{ok:sim.issueOrder("regroup",null,intent.unitId),message:"Protection directive accepted; NEREUS will assign a screen."};case"repair":return{ok:sim.issueOrder("repairs",null,intent.unitId),message:"Repair authorization issued to NEREUS."};case"shadow":return{ok:false,message:"Shadow assignment is not currently supported by a validated action."};case"directive":sim.updateFleetDirectives({[intent.field]:intent.value});return{ok:true,message:`${intent.field} directive applied.`};case"networkPolicy":sim.updateNetworkPolicy(intent.value,sim.network.posture);return{ok:true,message:"Network policy applied."};case"networkPosture":sim.updateNetworkPolicy(sim.network.policy,intent.value);return{ok:true,message:"Communication posture applied."};case"relay":{const unit=intent.unitId?sim.unit(intent.unitId):sim.units.find(u=>u.role==="ECHO"&&u.state==="active");return{ok:!!unit&&sim.deployRelay(unit.id),message:unit?`Relay deployment assigned to ${unit.callsign}.`:"No relay-capable unit is available."};}case"authorizeNeutralization":if(!sim.minefield)return{ok:false,message:"No minefield neutralization operation is active."};sim.updateMinefieldSettings({neutralizationAuthorized:true,neutralizationCancelled:false});return{ok:true,message:"Blocking-threat neutralization authorized."};case"authorizeDefense":if(!sim.echoRidge)return{ok:false,message:"No defensive operation is active."};sim.updateDefenseSettings({roe:"defensive"});return{ok:true,message:"Defensive action authorized against confirmed hostiles."};case"doctrine":sim.setDoctrine(intent.value);return{ok:true,message:`${intent.value} doctrine applied.`};}}
