import { FleetDirectives, Vec3 } from "../types";

export type CommandIntent =
  | { kind:"hold"|"resume"|"regroup"|"retreat"|"extract"|"cancel" }
  | { kind:"investigate"|"focus"; targetId:string|null; pos:Vec3|null }
  | { kind:"protect"|"repair"|"shadow"; unitId:string|null }
  | { kind:"directive"; field:keyof FleetDirectives; value:string }
  | { kind:"networkPolicy"; value:"full"|"degraded"|"planned"|"auto" }
  | { kind:"networkPosture"; value:"burst"|"balanced"|"continuous" }
  | { kind:"relay"; unitId:string|null }
  | { kind:"authorizeNeutralization"|"authorizeDefense" }
  | { kind:"doctrine"; value:"silent"|"balanced"|"urgent" };

export interface CommandEntity {id:string;label:string;kind:"unit"|"contact"|"objective";pos?:Vec3;classification?:string;manual?:boolean;connected?:boolean;}
export interface CommandContext {entities:CommandEntity[];selectedUnitId:string|null;selectedContactId:string|null;revision:number;}
export type ParseResult=
  |{status:"ready";intent:CommandIntent;canonical:string;target:string;consequence:string;confirmation:"routine"|"consequential"|"critical";revision:number}
  |{status:"clarification"|"target-required"|"invalid";message:string;candidates?:CommandEntity[]};

export function normalizeCommand(input:string){return input.normalize("NFKC").toLowerCase().replace(/[’‘]/g,"'").replace(/\b(metres?|meters?)\b/g,"m").replace(/\bplease\b|\bcan you\b|\bcould you\b/g," ").replace(/[^a-z0-9%+\-.,/\s]/g," ").replace(/\s+/g," ").trim();}

function entity(text:string,ctx:CommandContext,kind?:CommandEntity["kind"]):CommandEntity|null|"ambiguous"{const pool=ctx.entities.filter(e=>!kind||e.kind===kind);const exact=pool.filter(e=>text.includes(e.id.toLowerCase())||text.includes(e.label.toLowerCase()));if(exact.length===1)return exact[0];if(exact.length>1)return"ambiguous";return null;}
const ready=(intent:CommandIntent,canonical:string,target:string,consequence:string,confirmation:ParseResult extends never?never:"routine"|"consequential"|"critical",revision:number):ParseResult=>({status:"ready",intent,canonical,target,consequence,confirmation,revision});

export function parseCommand(input:string,ctx:CommandContext):ParseResult{const t=normalizeCommand(input);if(!t)return{status:"invalid",message:"Enter a command."};if(/\b(cancel|never mind|stand down directive)\b/.test(t))return ready({kind:"cancel"},"Cancel current directive","Current directive","NEREUS will supersede the active operator directive.","routine",ctx.revision);
  if(/tight escort/.test(t))return ready({kind:"directive",field:"formation",value:"escort"},"Tight escort directive","Fleet directives","NEREUS will validate tight escort against current terrain and mission constraints.","routine",ctx.revision);
  if(/\b(proceed to extraction|go to extraction|leave mission area|extract)\b/.test(t))return ready({kind:"extract"},"Proceed to extraction","Fleet","Mission work may be abandoned for extraction.","consequential",ctx.revision);
  if(/\b(hold|stop fleet|wait outside)\b/.test(t))return ready({kind:"hold"},"Hold fleet","Fleet","All reachable submarines will establish safe holding positions.","routine",ctx.revision);
  if(/\b(resume|continue|proceed)\b/.test(t))return ready({kind:"resume"},"Resume autonomy","Fleet","NEREUS will resume the validated mission plan.","routine",ctx.revision);
  if(/\b(regroup|rally|reassemble)\b/.test(t))return ready({kind:"regroup"},"Regroup fleet","Fleet","NEREUS will choose a safe common rally point.","routine",ctx.revision);
  if(/\b(retreat|withdraw|fall back)\b/.test(t))return ready({kind:"retreat"},"Emergency retreat","Fleet","Current assignments will be replaced by safe withdrawal routes.","critical",ctx.revision);
  if(/\b(protect|protected|screen|guard|escort)\b/.test(t)){let e=entity(t,ctx,"unit");if(!e&&ctx.selectedUnitId)e=ctx.entities.find(x=>x.id===ctx.selectedUnitId)??null;if(e==="ambiguous")return{status:"clarification",message:"Select the vessel or objective you want protected."};if(!e)return{status:"clarification",message:"Select the vessel or objective you want protected."};return ready({kind:"protect",unitId:e.id},`Protect ${e.label}`,e.label,`${e.manual?"The remaining autonomous fleet":"Lancer and suitable vessels"} will screen ${e.label}.`,"routine",ctx.revision);}
  if(/\b(repair|rescue|recover vessel)\b/.test(t)){const e=entity(t,ctx,"unit")||ctx.entities.find(x=>x.id===ctx.selectedUnitId);if(!e||e==="ambiguous")return{status:"clarification",message:"Select the vessel that needs repair."};return ready({kind:"repair",unitId:e.id},`Repair ${e.label}`,e.label,"Mender will be assigned if the approach is safe and supplies remain.","consequential",ctx.revision);}
  if(/\b(investigate area|scan area)\b/.test(t))return{status:"target-required",message:"Select a contact or world position to investigate."};
  if(/\b(investigate|inspect|check|scan contact)\b/.test(t)){const explicit=/\b[hm]-\d+\b/.test(t),resolved=entity(t,ctx,"contact"),e=resolved||(explicit?null:ctx.entities.find(x=>x.id===ctx.selectedContactId));if(e==="ambiguous")return{status:"clarification",message:"Which contact should be investigated?",candidates:ctx.entities.filter(x=>x.kind==="contact")};if(!e)return{status:"target-required",message:"Select a contact or world position to investigate."};return ready({kind:"investigate",targetId:e.id,pos:e.pos??null},`Investigate ${e.label}`,e.label,"NEREUS will assign a sensor-capable submarine and supporting cover.","routine",ctx.revision);}
  if(/\b(focus point|move to|advance to)\b/.test(t)){const e=entity(t,ctx);if(!e||e==="ambiguous")return{status:"target-required",message:"Select a valid world position."};return ready({kind:"focus",targetId:e.id,pos:e.pos??null},`Focus on ${e.label}`,e.label,"NEREUS will distribute approach and support tasks.","routine",ctx.revision);}
  if(/\b(relay|maintain communication|communication with)\b/.test(t)){const e=entity(t,ctx,"unit")||ctx.entities.find(x=>x.id===ctx.selectedUnitId);if(/deploy|establish|operate as/.test(t))return ready({kind:"relay",unitId:e&&e!=="ambiguous"?e.id:null},"Establish relay",e&&e!=="ambiguous"?e.label:"NEREUS-selected unit","A finite relay will be deployed at a reachable position.","consequential",ctx.revision);return ready({kind:"networkPolicy",value:"full"},"Maintain full connection",e&&e!=="ambiguous"?e.label:"Fleet","NEREUS will prioritize network coverage and relay placement.","routine",ctx.revision);}
  if(/authorize.*neutral|clear.*mine/.test(t))return ready({kind:"authorizeNeutralization"},"Authorize blocking-threat neutralization","Confirmed blocking threat","Limited defensive resources may be consumed.","critical",ctx.revision);
  if(/authorize.*defens|engage confirmed/.test(t))return ready({kind:"authorizeDefense"},"Authorize defensive action","Confirmed hostile contacts","Lancer may engage legal threats under current safety constraints.","critical",ctx.revision);
  const mappings:[RegExp,keyof FleetDirectives,string,string][]=[[/line ahead/,"formation","line","Line ahead"],[/wedge/,"formation","wedge","Wedge"],[/defensive ring|ring formation/,"formation","ring","Defensive ring"],[/wide search|search formation/,"formation","search","Wide search"],[/tight escort/,"formation","escort","Tight escort"],[/silent speed|slow and quiet/,"speed","silent","Silent"],[/cruise speed/,"speed","cruise","Cruise"],[/flank speed|maximum speed|full speed/,"speed","flank","Flank"],[/match.*slowest/,"speed","slowest","Match slowest"],[/shallow/,"depth","shallow","Shallow"],[/midwater|mid water/,"depth","mid","Midwater"],[/deep/,"depth","deep","Deep"],[/terrain follow/,"depth","terrain","Terrain following"],[/passive sensor|passive emission|passive only/,"emissions","passive","Passive sensors only"],[/active sonar when needed|active when needed/,"emissions","needed","Active when needed"],[/maximum awareness|max detection/,"emissions","maximum","Maximum awareness"],[/stay together|keep.*together/,"cohesion","together","Stay together"],[/task groups|split fleet/,"cohesion","groups","Task groups"],[/independent assignment/,"cohesion","independent","Independent assignments"],[/conservative risk|safest/,"risk","conservative","Conservative"],[/balanced risk/,"risk","balanced","Balanced"],[/mission focused|mission first/,"risk","mission","Mission focused"]];for(const[m,f,v,label]of mappings)if(m.test(t))return ready({kind:"directive",field:f,value:v},`${label} directive`,"Fleet directives",`NEREUS will validate ${label.toLowerCase()} against current terrain and mission constraints.`,v==="flank"||v==="independent"||v==="mission"?"consequential":"routine",ctx.revision);
  if(/go silent|silent running/.test(t))return ready({kind:"doctrine",value:"silent"},"Silent running","Fleet","Speed and avoidable emissions will be reduced.","routine",ctx.revision);if(/^balanced$|balanced doctrine/.test(t))return ready({kind:"doctrine",value:"balanced"},"Balanced doctrine","Fleet","NEREUS will balance speed, safety, and reserves.","routine",ctx.revision);if(/urgent doctrine|mission urgency/.test(t))return ready({kind:"doctrine",value:"urgent"},"Urgent doctrine","Fleet","NEREUS will accept higher exposure while preserving collision safety.","consequential",ctx.revision);
  if(/planned disconnect|permit.*disconnect/.test(t))return ready({kind:"networkPolicy",value:"planned"},"Permit planned disconnection","Fleet network","Units may execute acknowledged fallback plans without a live link.","consequential",ctx.revision);if(/allow degraded/.test(t))return ready({kind:"networkPolicy",value:"degraded"},"Allow degraded links","Fleet network","NEREUS may accept delayed telemetry and increased uncertainty.","routine",ctx.revision);if(/continuous.*link/.test(t))return ready({kind:"networkPosture",value:"continuous"},"Continuous command link","Fleet network","Higher emissions maintain frequent telemetry.","consequential",ctx.revision);if(/silent burst/.test(t))return ready({kind:"networkPosture",value:"burst"},"Silent burst communication","Fleet network","Telemetry updates will be less frequent and less detectable.","routine",ctx.revision);
  if(/^stop$/.test(t))return{status:"clarification",message:"Do you want to hold the fleet, abort the current plan, or stop the manually controlled submarine?"};return{status:"invalid",message:"Command not recognized or contains unsupported terms."};}
