import{describe,expect,it}from"vitest";import{Nereus}from"../src/ai/nereus";import{SIM}from"../src/config";import{hashSeed}from"../src/rng";import{Simulation}from"../src/sim/simulation";import{generateAbyssalCrownScenario}from"../src/world/mission";
function make(seedText="CROWN",difficulty:"easy"|"normal"|"hard"="normal"){const seed=hashSeed(seedText),sim=new Simulation(seed,difficulty,generateAbyssalCrownScenario(seed,difficulty)),nereus=new Nereus(sim);sim.onEvent=e=>nereus.onEvent(e);return{sim,nereus};}function run(sim:Simulation,n:Nereus,s:number){for(let i=0;i<s/SIM.DT&&!sim.outcome;i++){sim.step();n.update();}}
describe("Operation Abyssal Crown",()=>{
 it("progresses through all director phases and wins under autonomy",()=>{const{sim,nereus}=make();run(sim,nereus,1500);expect(sim.outcome).toBe("won");expect(sim.crown!.phase).toBe("complete");for(const p of["insertion","canyon","network","minefield","defense","core","extraction"])expect(sim.crown!.completed.has(p as never)).toBe(true);});
 it("safe and short canyon branches are deterministic",()=>{const a=make("BRANCH"),b=make("BRANCH");a.sim.crown!.canyonChoice="short";b.sim.crown!.canyonChoice="short";run(a.sim,a.nereus,260);run(b.sim,b.nereus,260);expect(a.sim.crown!.phase).toBe(b.sim.crown!.phase);expect(a.sim.units.map(u=>[u.pos.x,u.pos.z])).toEqual(b.sim.units.map(u=>[u.pos.x,u.pos.z]));});
 it("planned disconnection branch still recovers",()=>{const{sim,nereus}=make();sim.crown!.networkChoice="planned";run(sim,nereus,1500);expect(sim.coreState).toBe("carried");expect(sim.outcome).toBe("won");});
 it("survives one manual intervention",()=>{const{sim,nereus}=make();run(sim,nereus,100);const ghost=sim.units.find(u=>u.role==="GHOST")!,token=sim.acquireManualControl(ghost.id)!;sim.setManualCommand(token,{heading:ghost.heading+.4,throttle:5});run(sim,nereus,10);sim.releaseManualControl(token);run(sim,nereus,1390);expect(sim.outcome).toBe("won");});
 it("recovers from fleet damage with three survivors",()=>{const{sim,nereus}=make();sim.damageUnit(sim.units[1],10000,"test");sim.damageUnit(sim.units[2],10000,"test");run(sim,nereus,1500);expect(sim.aliveUnits()).toHaveLength(3);expect(sim.outcome).toBe("won");});
 it("fails with fewer than three survivors",()=>{const{sim,nereus}=make();for(const u of sim.units.slice(0,3))sim.damageUnit(u,10000,"test");run(sim,nereus,2);expect(sim.outcome).toBe("lost");expect(sim.crown!.phase).toBe("failed");});
 it("reproduces progression under another seed",()=>{const a=make("CROWN-2"),b=make("CROWN-2");run(a.sim,a.nereus,1500);run(b.sim,b.nereus,1500);expect(a.sim.outcome).toBe(b.sim.outcome);expect(a.sim.crown!.completed).toEqual(b.sim.crown!.completed);});
});
