import{describe,expect,it}from"vitest";import{Nereus}from"../src/ai/nereus";import{SIM}from"../src/config";import{hashSeed}from"../src/rng";import{Simulation}from"../src/sim/simulation";import{generateEchoRidgeScenario}from"../src/world/mission";
function make(){const seed=hashSeed("RIDGE"),sim=new Simulation(seed,"normal",generateEchoRidgeScenario(seed)),nereus=new Nereus(sim);sim.onEvent=e=>nereus.onEvent(e);return{sim,nereus};}function run(sim:Simulation,n:Nereus,s:number){for(let i=0;i<s/SIM.DT;i++){sim.step();n.update();}}
describe("Echo Ridge defense",()=>{
 it("hostiles begin without fleet knowledge",()=>{const{sim}=make();expect(sim.hostileDrones.every(d=>d.targetId===null&&d.lastKnownTargetPos===null)).toBe(true);expect(sim.echoRidge!.contacts.size).toBe(0);});
 it("mobile contact classification progresses from observations",()=>{const{sim,nereus}=make();for(const u of sim.units)u.pos={x:0,y:-130,z:-300};run(sim,nereus,50);expect(sim.echoRidge!.contacts.size).toBeGreaterThan(0);expect([...sim.echoRidge!.contacts.values()].some(c=>c.classification!=="unknownMobile")).toBe(true);});
 it("hostile attacks travel and create warning time",()=>{const{sim,nereus}=make();const drone=sim.hostileDrones[1],target=sim.units[0];drone.pos={x:target.pos.x+220,y:target.pos.y,z:target.pos.z};drone.suspicion=1;drone.targetId=target.id;drone.lastKnownTargetPos={...target.pos};drone.state="attack";run(sim,nereus,1);expect(sim.projectiles.some(p=>p.fromNodeId===drone.id&&!p.done)).toBe(true);});
 it("manual ownership remains exclusive while defense plans continue",()=>{const{sim,nereus}=make();run(sim,nereus,2);const token=sim.acquireManualControl(sim.units[1].id)!;run(sim,nereus,3);expect(sim.manualOwnerId).toBe(sim.units[1].id);expect(sim.units.filter(u=>u.id!==token.unitId&&u.control.mode==="autonomous")).toHaveLength(4);});
 it("reinforcement spawns outside initial knowledge and resets with scenario",()=>{const a=make();expect(a.sim.introduceReinforcement()).toBe(true);expect(a.sim.hostileDrones).toHaveLength(4);expect(a.sim.echoRidge!.contacts.has("H-04")).toBe(false);const b=make();expect(b.sim.hostileDrones).toHaveLength(3);});
 it("rules of engagement gate defensive interceptor launch",()=>{const{sim}=make();const lancer=sim.units.find(u=>u.role==="LANCER")!,drone=sim.hostileDrones[0];sim.echoRidge!.contacts.set(drone.id,{id:drone.id,estimate:{...drone.pos},uncertainty:10,classification:"hostile",evidence:1,heading:0,speed:8,lastDetected:0,detectingUnitId:lancer.id,behavior:"attack",suspectedTargetId:lancer.id,damageState:"intact"});drone.pos={x:lancer.pos.x+300,y:lancer.pos.y,z:lancer.pos.z};sim.echoRidge!.roe="evade";expect(sim.launchDefensiveInterceptor(drone.id)).toBe(false);sim.echoRidge!.roe="defensive";for(const u of sim.units)if(u.id!==lancer.id)u.pos={x:-1200,y:-130,z:600};expect(sim.launchDefensiveInterceptor(drone.id)).toBe(true);expect(sim.projectiles.some(p=>p.targetId===`drone:${drone.id}`)).toBe(true);});
 it("countermeasure degrades a tracking hostile",()=>{const{sim}=make();const drone=sim.hostileDrones[0],unit=sim.units[3];drone.pos={x:unit.pos.x+100,y:unit.pos.y,z:unit.pos.z};drone.suspicion=1;drone.state="track";expect(sim.deployCountermeasure(unit.id)).toBe(true);expect(drone.suspicion).toBeLessThan(1);expect(drone.state).toBe("evade");});
  it("recovers the package and reaches a terminal outcome",()=>{const{sim,nereus}=make();run(sim,nereus,1800);expect(sim.outcome).toBe("won");expect(sim.echoRidge!.packageState).toBe("delivered");});
  it("loses when the package carrier is destroyed",()=>{const{sim,nereus}=make();run(sim,nereus,2);const carrier=sim.units.find(u=>u.role==="MENDER")!;carrier.pos={...sim.mission.echoRidge!.packagePos};sim.step();nereus.update();expect(sim.echoRidge!.packageState).toBe("carried");sim.damageUnit(carrier,10000,"test");expect(sim.outcome).toBe("lost");expect(sim.echoRidge!.packageState).toBe("lost");});
  it("loses when fewer than three submarines survive",()=>{const{sim,nereus}=make();for(const u of sim.units.slice(0,3))sim.damageUnit(u,10000,"test");run(sim,nereus,1);expect(sim.outcome).toBe("lost");});
  it("loses when the operation window expires",()=>{const{sim,nereus}=make();sim.timeRemaining=0.1;run(sim,nereus,1);expect(sim.outcome).toBe("lost");expect(sim.loseReason).toContain("window");});
});
