import{describe,expect,it}from"vitest";import{Nereus}from"../src/ai/nereus";import{SIM}from"../src/config";import{hashSeed}from"../src/rng";import{Simulation}from"../src/sim/simulation";import{generateSilentDivideScenario}from"../src/world/mission";
function make(){const seed=hashSeed("DIVIDE"),sim=new Simulation(seed,"normal",generateSilentDivideScenario(seed)),nereus=new Nereus(sim);sim.onEvent=e=>nereus.onEvent(e);return{sim,nereus};}function run(sim:Simulation,n:Nereus,s:number){for(let i=0;i<s/SIM.DT;i++){sim.step();n.update();}}
describe("fleet network",()=>{
 it("Mender traverses the post-relay route and recovers the black box",()=>{const{sim,nereus}=make();sim.network.relays.push({id:"relay-test",pos:{x:-650,y:-125,z:220},range:1200,energy:100,active:true,deployedBy:"test"});sim.silentDivideState!.phase="recovery";sim.silentDivideState!.assignmentRevision=100;run(sim,nereus,500);const m=sim.units.find(u=>u.role==="MENDER")!;expect(sim.coreState).toBe("carried");expect(m.hasCore).toBe(true);});
 it("maintains direct links in clear range",()=>{const{sim,nereus}=make();for(const u of sim.units)u.pos={x:-1000+(sim.units.indexOf(u)*30),y:-125,z:0};run(sim,nereus,2);expect([...sim.network.links.values()].every(l=>l.state!=="disconnected")).toBe(true);});
 it("uses a deployed relay for a separated vessel",()=>{const{sim,nereus}=make();const echo=sim.units.find(u=>u.role==="ECHO")!,ghost=sim.units.find(u=>u.role==="GHOST")!;for(const u of sim.units)if(u.id!==ghost.id)u.pos={x:-1000,y:-80,z:1100};echo.pos={x:-650,y:-80,z:1100};expect(sim.deployRelay(echo.id)).toBe(true);for(const u of sim.units)if(u.id!==ghost.id)u.pos={x:-1000,y:-80,z:1100};ghost.pos={x:-320,y:-80,z:1100};run(sim,nereus,.5);expect(sim.network.links.get(ghost.id)!.route).toContain("relay-1");});
 it("terrain interference degrades or disconnects links with hysteresis",()=>{const{sim,nereus}=make();const ghost=sim.units.find(u=>u.role==="GHOST")!;ghost.pos={...sim.mission.silentDivide!.deadZoneCenter};sim.activateUnknownJammer();run(sim,nereus,3);expect(["degraded","disconnected"].includes(sim.network.links.get(ghost.id)!.state)).toBe(true);});
 it("prioritizes, delays, expires and acknowledges messages",()=>{const{sim,nereus}=make();const ghost=sim.units[1];const high=sim.queueNetworkMessage("operator",ghost.id,"manual",90,5),low=sim.queueNetworkMessage("NEREUS",ghost.id,"assignment",20,.1);run(sim,nereus,2);expect(high.state).toBe("delivered");expect(high.acknowledged).toBe(true);expect(low.state).toBe("expired");});
 it("disconnect expires manual lease and activates fallback",()=>{const{sim,nereus}=make();const ghost=sim.units.find(u=>u.role==="GHOST")!,token=sim.acquireManualControl(ghost.id)!;expect(token).toBeTruthy();ghost.pos={...sim.mission.silentDivide!.deadZoneCenter};sim.activateUnknownJammer();run(sim,nereus,4);expect(sim.manualOwnerId).toBeNull();expect(ghost.task.desc).toContain("fallback");});
  it("reset creates clean relays, messages and jammer state",()=>{const a=make();a.sim.deployRelay(a.sim.units[0].id);a.sim.activateUnknownJammer();a.sim.queueNetworkMessage("a",a.sim.units[1].id,"assignment",1,2);const b=make();expect(b.sim.network.relays).toHaveLength(0);expect(b.sim.network.messages).toHaveLength(0);expect(b.sim.network.jammerActive).toBe(false);});
  it("bounds retained network message history",()=>{const {sim}=make();for(let i=0;i<200;i++)sim.queueNetworkMessage("operator",sim.units[1].id,"assignment",1,2);expect(sim.network.messages).toHaveLength(120);expect(sim.network.messages[0].id).toBe("net-81");});
 it("recovers the black box and completes extraction",()=>{const{sim,nereus}=make();run(sim,nereus,1400);expect(sim.coreState).toBe("carried");expect(sim.outcome).toBe("won");});
});
